# nsutils: namespace utilities
# Copyright (C) 2022  Guilherme Janczak <guilherme.janczak@yandex.com>
#
# build-and-test.yml: Github Actions automated testing
#
# Cado is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; If not, see <http://www.gnu.org/licenses/>.

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.1
      - name: install
        run: |
          sudo apt update
          sudo apt upgrade gcc autoconf libbsd-dev libcap-dev
      - name: setup
        run: |
          autoreconf -if
          ./configure
      - name: build
        run: make

